services:
  - type: web
    name: lotto-api
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -U pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
